### PR TITLE
reset button in partial

### PR DESCRIPTION
**Pull request by babelarr**
Hi girls, please check the reset button code in partial. It only doesn't work in skills.

Thank youu!! :)

### CODE REVIEW

**Comment by babelarr** [comment]
Reset skills are resolved too with the last commit

**Comment by babelarr** [comment]
Skills are fixed, please check it for merge with dev

Thank you!! :)

**Comment by babelarr** [comment]
dataJason get all values form and we can reset them with the Reset button.

**Comment by esterlegaz** [comment]
Perfect! You can merge it and I think now I can continue with my branch :)

**Review by esterlegaz — APPROVED** [review]

**Pull request merged**
