### PR TITLE
Api skills

### PR DESCRIPTION
**Pull request by chicainoportuna**
Limit number of checkbox selections at skills is complete! Or I think so.
Could you review it? 
Thanks :)

### CODE REVIEW

**Comment by babelarr** [comment]
We have to delete the commented code in fill_card.html

**Comment by japocoinyenhoang** [comment]
Hi Paula,
we do have to conflicting files in :
Conflicting files
_src/assets/js/main.js
_src/templates/partials/_fill_card.html

one of them is thet we just create two const with diferent names that could me use only as one :
const skillsCheckList = document.querySelectorAll('.skills__checkbox');
=======
const checkList = document.querySelectorAll('.skills__checkbox');
what do you prefer??? Do you want me to change my code  or you would change yours?.

and the other one we cal solve it oruself because we had to create a new container to make it colapsable.

so, please,  let me know if i you prefer to change the name of your const or not.
Thanks for your attention.

**Comment by chicainoportuna** [comment]
Thanks, Yen!
Please, feel free to to change your code for fixing de duplicate constants :) 

Of course we should delete the commented code, Laura, thank you!

**Comment by chicainoportuna** [comment]
Yeah! 👍

**Pull request merged**
